services:
  edu-communication:
    build: .
    container_name: edu-cm
    restart: unless-stopped
    ports:
      - '3099:3099'
    volumes:
      - ./edu/logs:/logs
    logging:
      driver: "json-file"
      options:
        max-size: "20MB"
        max-file: "5"
